### ISSUE TITLE
CLI Version 命令行版本

### ISSUE THREAD

**Issue by rsp4jack** [wave2midi/SingingPiano#2]
首先，衷心祝贺此项目在 GitHub 上线，这也是我许久的愿望。
回到主题，此工具设计的很好，Qt GUI 设计的十分美观实用。
但这引申到一个问题：我并不能在所有条件下都使用 Qt GUI
版本，例如说我没有加载桌面环境，或者 PyQt 损坏无法使用
等。
我虽然在项目根目录下找到了一个名为“singingpiano.py"的文件，
但我不知道怎么去使用。况且这种交互式执行很影响自动化执行，
并且这个文件看起来似乎已被弃置多年，不再维护。
综上所述，希望开发团队能设计一个 CLI+交互式 的 Python 脚本文件，
以方便无法使用 GUI 的用户以及自动化执行脚本。

**Comment by Mewnojs** [comment]
感谢您的祝贺。
关于您提出的问题作如下解答：
实际上Qt版本整合的只是GUI，调用的还是原本的singingpiano.py。但目前这个文件没有命令解析功能（此前的实现过于混乱因此删除了），执行之则会运行测试用例（其行为是以默认参数将目录下in.wav转换为out.mid并输出）。
正在考虑重写这一部分，按照POSIX标准。
面包会有的，牛奶也会有的。

**Comment by Mewnojs** [comment]
问题已解决。现在可以通过运行singingpiano.py直接执行转换，并支持对多个文件按顺序转换。
