### ISSUE TITLE
pip没有-r

### ISSUE THREAD

**Issue by dffxd-suntra** [wave2midi/SingingPiano#6]
C:\Users\Administrator\Desktop\SingingPiano-master>pip -r requirments.txt

Usage:
  pip <command> [options]

no such option: -r

**Comment by Mewnojs** [comment]
> C:\Users\Administrator\Desktop\SingingPiano-master>pip -r requirments.txt
> 
> Usage:
>   pip <command> [options]
> 
> no such option: -r
> 

这是由于文档写错了导致的，正确的命令是
pip install -r requirements.txt

**Comment by dffxd-suntra** [comment]
> > C:\Users\Administrator\Desktop\SingingPiano-master>pip -r requirments.txt
> > Usage:
> > pip  [options]
> > no such option: -r
> 
> 这是由于文档写错了导致的，正确的命令是 pip install -r requirements.txt

🆗我试试
